<a href="https://colab.research.google.com/github/rikanga/Easy-Numpy/blob/main/DimensionalityReductionUsingFeatureSelection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dimentionality Reduction Using Feature Selection

Deux façons de réduire la dimension:

* Avec du feature extraction(PCA, KernelPCA, NMF, TruncatedSVD, LineaderDiscriminantAnalysis ...)
* Et avec du feature selection que nous voyons maintenant

Ici nous allons  voir comment récupérer certaines fonctionnalités en se basant sur la qualité de ce dernières, sur les caractéristiques les plus informatives

Trois methodes dans le feature selection:

* filter
* wrapper
* embadded

La methode **filter**, Sélectionne les caractéristiques importantes en se basant sur les propriétés statistiques;

La methode **wrapper**, Trouve un échantillon des données qui permettrai d'avoir une haute qualité de la prédiction

## 10.1 Thresholding Numerical Feature Variance

**Problème**

Vous disposez d'un ensemble d'entités numériques et souhaitez supprimer celles dont la variance est faible (c'est-à-dire qui contiennent probablement peu d'informations).

**Solution**

Sélectionnez un sous-ensemble de caractéristiques avec des variances supérieures à un seuil donné :

In [12]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt

In [1]:
# Load libraries
from sklearn.datasets import load_iris
from sklearn.feature_selection import VarianceThreshold

In [2]:
#  Load data
iris = load_iris()

In [4]:
# Create features and targets
features = iris.data
target = iris.target

In [5]:
# Create thresholder
tresholder = VarianceThreshold(threshold=0.5)

In [6]:
# Create high variance feature matrix
features_high_variance = tresholder.fit_transform(features)

In [8]:
print("Original dimension", features.shape)
print("Dimension Selected", features_high_variance.shape)

Original dimension (150, 4)
Dimension Selected (150, 3)


In [9]:
features[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [11]:
features_high_variance[:5]

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5. , 1.4, 0.2]])

In [16]:
np.var(features, axis=0)

array([0.68112222, 0.18871289, 3.09550267, 0.57713289])

In [20]:
# Show the variance
tresholder.fit(features).variances_

array([0.68112222, 0.18871289, 3.09550267, 0.57713289])