<a href="https://colab.research.google.com/github/rikanga/Easy-Numpy/blob/main/ML_UP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Flattening a matrix

In [1]:
import numpy as np

In [2]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [3]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
matrix.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Loading a Sample Dataset

In [5]:
from sklearn import datasets

In [6]:
# Load digits matrix
digits = datasets.load_digits()

In [7]:
# Create features matrix
features = digits.data

In [8]:
# Create target matrix
target = digits.target

In [9]:
features[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

## Creating a Simulated Dataset

In [10]:
from sklearn.datasets import make_regression, make_classification, make_blobs

In [12]:
features, target, coefficients = make_regression(
    n_samples = 100,
    n_features = 3,
    n_informative = 1,
    n_targets = 1,
    noise = 0.0,
    coef = True,
    random_state = 1
)

In [13]:
features[0]

array([ 0.86888616, -0.10174587,  0.75041164])

In [29]:
features[:, 0]

array([ 0.86888616,  0.0465673 ,  0.58281521, -0.39675353,  0.74055645,
       -0.22631424,  1.1110567 , -0.51709446, -0.26788808,  2.52832571,
       -1.76068856, -0.29736188,  0.92145007,  0.1094027 ,  2.05117344,
       -0.43495668, -0.11044703,  1.54335911, -0.54577417, -0.7612069 ,
       -1.85798186,  0.98633519, -1.44411381, -0.56230543, -0.68372786,
       -0.44317193, -0.95542526, -0.19183555,  0.84616065,  0.2344157 ,
        1.25286816, -0.30620401,  0.68006984,  0.66102029, -2.43483776,
       -0.86131636,  1.46210794, -0.38405435,  0.48851815,  1.23225307,
        0.59357852, -1.1191154 , -0.29664115,  0.86540763,  0.0809271 ,
        0.76201118,  0.03261455,  1.6924546 ,  0.90159072,  0.31354772,
       -0.44712856,  1.20205486, -0.61175641, -1.31228341,  0.87616892,
        1.6169496 , -1.1425182 ,  0.61720311,  0.5505375 , -0.77516162,
        1.93752881,  1.12141771,  1.04444209,  0.79502609,  0.3380117 ,
        1.16033857, -0.31098498, -1.67419581, -1.23312074,  0.60

In [30]:
print("Feature Matrix\n", features[:3])
print("Target maxtrix\n",  target[:3])

Feature Matrix
 [[ 0.86888616 -0.10174587  0.75041164]
 [ 0.0465673   0.80186103 -0.18656977]
 [ 0.58281521  0.04221375 -1.10061918]]
Target maxtrix
 [-4.49619366 35.43458225  1.86544354]


#  **3. Data Wrangling**

## 3.1 Loading CSV File

**Probel**

We need to load the comma separeted values(CSV) file

In [31]:
import pandas as pd

In [38]:
#Create URL
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'

In [39]:
#dataframe = pd.read_csv(url)
dataframe = pd.read_csv(url)

In [40]:
dataframe.head()

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

## 3.2 Create a DataFrame

In [41]:
# Create DataFrame
dataframe = pd.DataFrame()

In [42]:
# Add columns to the data set
dataframe["Name"] = ["Jacky Jackson", "Steven Stevenson"]
dataframe["Age"] = [38, 25]
dataframe["Driver"] = [True, False]

In [43]:
dataframe

Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False

In [44]:
# Add a new person
new_person = pd.Series(['Molly Mooney', 40, True], index=['Name', 'Age', 'Driver'])

In [47]:
# Append row
dataframe.append(new_person, ignore_index=True)

Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False
2      Molly Mooney   40    True

## 3.2 Describing the Data

In [48]:
#Create URL
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'

In [49]:
# Load data
dataframe = pd.read_csv(url)

In [52]:
# Show two rows
dataframe.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [53]:
# Show dimensions
dataframe.shape

(1313, 6)

In [54]:
#Show statistics
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

## 3.3 Navigating DataFrames

In [55]:
# Select first row
dataframe.iloc[0]

Name        Allen, Miss Elisabeth Walton
PClass                               1st
Age                                 29.0
Sex                               female
Survived                               1
SexCode                                1
Name: 0, dtype: object

In [60]:
# Select tree rows
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

In [62]:
# Another way to select three first row
dataframe.iloc[:3]

Name PClass   Age     Sex  Survived  SexCode
0         Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1          Allison, Miss Helen Loraine    1st   2.0  female         0        1
2  Allison, Mr Hudson Joshua Creighton    1st  30.0    male         0        0

In [63]:
# Set index
dataframe.set_index("Name")

PClass    Age     Sex  Survived  \
Name                                                                            
Allen, Miss Elisabeth Walton                     1st  29.00  female         1   
Allison, Miss Helen Loraine                      1st   2.00  female         0   
Allison, Mr Hudson Joshua Creighton              1st  30.00    male         0   
Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female         0   
Allison, Master Hudson Trevor                    1st   0.92    male         1   
...                                              ...    ...     ...       ...   
Zakarian, Mr Artun                               3rd  27.00    male         0   
Zakarian, Mr Maprieder                           3rd  26.00    male         0   
Zenni, Mr Philip                                 3rd  22.00    male         0   
Lievens, Mr Rene                                 3rd  24.00    male         0   
Zimmerman, Leo                                   3rd  29.00    male         0   

                                               SexCode  
Name                                                    
Allen, Miss Elisabeth Walton                         1  
Allison, Miss Helen Loraine                          1  
Allison, Mr Hudson Joshua Creighton                  0  
Allison, Mrs Hudson JC (Bessie Waldo Daniels)        1  
Allison, Master Hudson Trevor                        0  
...                                                ...  
Zakarian, Mr Artun                                   0  
Zakarian, Mr Maprieder                               0  
Zenni, Mr Philip                                     0  
Lievens, Mr Rene                                     0  
Zimmerman, Leo                                       0  

[1313 rows x 5 columns]

In [64]:
# Another way to set index
dataframe.set_index(dataframe['Name'])

Name  \
Name                                                                                           
Allen, Miss Elisabeth Walton                                    Allen, Miss Elisabeth Walton   
Allison, Miss Helen Loraine                                      Allison, Miss Helen Loraine   
Allison, Mr Hudson Joshua Creighton                      Allison, Mr Hudson Joshua Creighton   
Allison, Mrs Hudson JC (Bessie Waldo Daniels)  Allison, Mrs Hudson JC (Bessie Waldo Daniels)   
Allison, Master Hudson Trevor                                  Allison, Master Hudson Trevor   
...                                                                                      ...   
Zakarian, Mr Artun                                                        Zakarian, Mr Artun   
Zakarian, Mr Maprieder                                                Zakarian, Mr Maprieder   
Zenni, Mr Philip                                                            Zenni, Mr Philip   
Lievens, Mr Rene                                                            Lievens, Mr Rene   
Zimmerman, Leo                                                                Zimmerman, Leo   

                                              PClass    Age     Sex  Survived  \
Name                                                                            
Allen, Miss Elisabeth Walton                     1st  29.00  female         1   
Allison, Miss Helen Loraine                      1st   2.00  female         0   
Allison, Mr Hudson Joshua Creighton              1st  30.00    male         0   
Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female         0   
Allison, Master Hudson Trevor                    1st   0.92    male         1   
...                                              ...    ...     ...       ...   
Zakarian, Mr Artun                               3rd  27.00    male         0   
Zakarian, Mr Maprieder                           3rd  26.00    male         0   
Zenni, Mr Philip                                 3rd  22.00    male         0   
Lievens, Mr Rene                                 3rd  24.00    male         0   
Zimmerman, Leo                                   3rd  29.00    male         0   

                                               SexCode  
Name                                                    
Allen, Miss Elisabeth Walton                         1  
Allison, Miss Helen Loraine                          1  
Allison, Mr Hudson Joshua Creighton                  0  
Allison, Mrs Hudson JC (Bessie Waldo Daniels)        1  
Allison, Master Hudson Trevor                        0  
...                                                ...  
Zakarian, Mr Artun                                   0  
Zakarian, Mr Maprieder                               0  
Zenni, Mr Philip                                     0  
Lievens, Mr Rene                                     0  
Zimmerman, Leo                                       0  

[1313 rows x 6 columns]

In [66]:
dataframe.set_index("Name", drop=False)

Name  \
Name                                                                                           
Allen, Miss Elisabeth Walton                                    Allen, Miss Elisabeth Walton   
Allison, Miss Helen Loraine                                      Allison, Miss Helen Loraine   
Allison, Mr Hudson Joshua Creighton                      Allison, Mr Hudson Joshua Creighton   
Allison, Mrs Hudson JC (Bessie Waldo Daniels)  Allison, Mrs Hudson JC (Bessie Waldo Daniels)   
Allison, Master Hudson Trevor                                  Allison, Master Hudson Trevor   
...                                                                                      ...   
Zakarian, Mr Artun                                                        Zakarian, Mr Artun   
Zakarian, Mr Maprieder                                                Zakarian, Mr Maprieder   
Zenni, Mr Philip                                                            Zenni, Mr Philip   
Lievens, Mr Rene                                                            Lievens, Mr Rene   
Zimmerman, Leo                                                                Zimmerman, Leo   

                                              PClass    Age     Sex  Survived  \
Name                                                                            
Allen, Miss Elisabeth Walton                     1st  29.00  female         1   
Allison, Miss Helen Loraine                      1st   2.00  female         0   
Allison, Mr Hudson Joshua Creighton              1st  30.00    male         0   
Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female         0   
Allison, Master Hudson Trevor                    1st   0.92    male         1   
...                                              ...    ...     ...       ...   
Zakarian, Mr Artun                               3rd  27.00    male         0   
Zakarian, Mr Maprieder                           3rd  26.00    male         0   
Zenni, Mr Philip                                 3rd  22.00    male         0   
Lievens, Mr Rene                                 3rd  24.00    male         0   
Zimmerman, Leo                                   3rd  29.00    male         0   

                                               SexCode  
Name                                                    
Allen, Miss Elisabeth Walton                         1  
Allison, Miss Helen Loraine                          1  
Allison, Mr Hudson Joshua Creighton                  0  
Allison, Mrs Hudson JC (Bessie Waldo Daniels)        1  
Allison, Master Hudson Trevor                        0  
...                                                ...  
Zakarian, Mr Artun                                   0  
Zakarian, Mr Maprieder                               0  
Zenni, Mr Philip                                     0  
Lievens, Mr Rene                                     0  
Zimmerman, Leo                                       0  

[1313 rows x 6 columns]

## 3.4 Selecting Rows Based on Conditionals

In [67]:
# show two rows where Sex is female
dataframe[dataframe['Sex'] == 'female'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [69]:
# Filer rows
dataframe[(dataframe["Sex"] == 'female') & (dataframe["Age"] >= 65)]

Name PClass   Age     Sex  \
73  Crosby, Mrs Edward Gifford (Catherine Elizabet...    1st  69.0  female   

    Survived  SexCode  
73         1        1

## 3.5 Replacing Values

In [70]:
# Replace values, show two rows
dataframe['Sex'].replace('female', 'Woman').head(2)

0    Woman
1    Woman
Name: Sex, dtype: object

In [71]:
dataframe["Sex"].replace(['female', 'male'], ['woman', 'man']).head()

0    woman
1    woman
2      man
3    woman
4      man
Name: Sex, dtype: object

In [72]:
dataframe['Sex'].replace({'female':'woman', 'male':"man"}).head()

0    woman
1    woman
2      man
3    woman
4      man
Name: Sex, dtype: object

In [73]:
dataframe.replace(1, 'One').head()

Name PClass   Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.0  female   
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   
4                  Allison, Master Hudson Trevor    1st  0.92    male   

  Survived SexCode  
0      One     One  
1        0     One  
2        0       0  
3        0     One  
4      One       0

In [77]:
dataframe.replace({"female":0, 'male':1})

Name PClass    Age  Sex  \
0                      Allen, Miss Elisabeth Walton    1st  29.00    0   
1                       Allison, Miss Helen Loraine    1st   2.00    0   
2               Allison, Mr Hudson Joshua Creighton    1st  30.00    1   
3     Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00    0   
4                     Allison, Master Hudson Trevor    1st   0.92    1   
...                                             ...    ...    ...  ...   
1308                             Zakarian, Mr Artun    3rd  27.00    1   
1309                         Zakarian, Mr Maprieder    3rd  26.00    1   
1310                               Zenni, Mr Philip    3rd  22.00    1   
1311                               Lievens, Mr Rene    3rd  24.00    1   
1312                                 Zimmerman, Leo    3rd  29.00    1   

      Survived  SexCode  
0            1        1  
1            0        1  
2            0        0  
3            0        1  
4            1        0  
...        ...      ...  
1308         0        0  
1309         0        0  
1310         0        0  
1311         0        0  
1312         0        0  

[1313 rows x 6 columns]

In [87]:
dataframe.replace(r'1st', 'First', regex=True).head()

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton  First  29.00  female   
1                    Allison, Miss Helen Loraine  First   2.00  female   
2            Allison, Mr Hudson Joshua Creighton  First  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)  First  25.00  female   
4                  Allison, Master Hudson Trevor  First   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

## 3.6 Renaming Columns

In [91]:
# Rename columns
dataframe.rename(columns={"PClass": 'Passenger Class'}).head()

Name Passenger Class    Age  \
0                   Allen, Miss Elisabeth Walton             1st  29.00   
1                    Allison, Miss Helen Loraine             1st   2.00   
2            Allison, Mr Hudson Joshua Creighton             1st  30.00   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)             1st  25.00   
4                  Allison, Master Hudson Trevor             1st   0.92   

      Sex  Survived  SexCode  
0  female         1        1  
1  female         0        1  
2    male         0        0  
3  female         0        1  
4    male         1        0

In [92]:
# Rename two columns
dataframe.rename(columns={"Pclass":"Passsenger Class", 'Sex':'Gender'}).head()

Name PClass    Age  Gender  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

**Empty columns**

In [93]:
import collections

In [94]:
column_names = collections.defaultdict(str)

In [95]:
for col in dataframe.columns:
  column_names[col]

column_names

defaultdict(str,
            {'Age': '',
             'Name': '',
             'PClass': '',
             'Sex': '',
             'SexCode': '',
             'Survived': ''})

## 3.7 Finding the Minimum,  Maximum, Sum, Average and Count

In [96]:
# calculate statistics
print("Maximum:", dataframe["Age"].max())
print("Maximum:", dataframe["Age"].min())
print("Mean:", dataframe["Age"].mean())
print("Sum:", dataframe["Age"].sum())
print("Count:", dataframe["Age"].count())

Maximum: 71.0
Maximum: 0.17
Mean: 30.397989417989415
Sum: 22980.88
Count: 756


In [98]:
# Show counts
dataframe.count()

Name        1313
PClass      1313
Age          756
Sex         1313
Survived    1313
SexCode     1313
dtype: int64

## 3.8 Finding Unique Values

In [100]:
dataframe["Sex"].unique()

array(['female', 'male'], dtype=object)

In [101]:
dataframe["Sex"].value_counts()

male      851
female    462
Name: Sex, dtype: int64

In [102]:
dataframe['PClass'].value_counts()

3rd    711
1st    322
2nd    279
*        1
Name: PClass, dtype: int64

In [103]:
dataframe['PClass'].unique()

array(['1st', '2nd', '*', '3rd'], dtype=object)

## 3.9 Handling Missinng Values

In [104]:
dataframe[dataframe["Age"].isnull()].head()

Name PClass  Age     Sex  Survived  SexCode
12  Aubert, Mrs Leontine Pauline    1st  NaN  female         1        1
13      Barkworth, Mr Algernon H    1st  NaN    male         1        0
14            Baumann, Mr John D    1st  NaN    male         0        0
29       Borebank, Mr John James    1st  NaN    male         0        0
32            Bradley, Mr George    1st  NaN    male         1        0

In [105]:
dataframe['Sex'] = dataframe['Sex'].replace('male', NaN)

NameError: ignored

In [106]:
import numpy as np

In [107]:
dataframe['Sex'] = dataframe['Sex'].replace("male", np.nan)

## 3.10 Deleting a Column

In [108]:
dataframe.drop('Age', axis=1).head()

Name PClass     Sex  Survived  \
0                   Allen, Miss Elisabeth Walton    1st  female         1   
1                    Allison, Miss Helen Loraine    1st  female         0   
2            Allison, Mr Hudson Joshua Creighton    1st     NaN         0   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  female         0   
4                  Allison, Master Hudson Trevor    1st     NaN         1   

   SexCode  
0        1  
1        1  
2        0  
3        1  
4        0

In [109]:
dataframe.drop(['Age', 'Sex'], axis=1).head()

Name PClass  Survived  SexCode
0                   Allen, Miss Elisabeth Walton    1st         1        1
1                    Allison, Miss Helen Loraine    1st         0        1
2            Allison, Mr Hudson Joshua Creighton    1st         0        0
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st         0        1
4                  Allison, Master Hudson Trevor    1st         1        0

## 3.11 Deleting a Row

In [111]:
dataframe[dataframe['Sex'] != 'female'].head()

Name PClass    Age  Sex  Survived  SexCode
2  Allison, Mr Hudson Joshua Creighton    1st  30.00  NaN         0        0
4        Allison, Master Hudson Trevor    1st   0.92  NaN         1        0
5                   Anderson, Mr Harry    1st  47.00  NaN         1        0
7               Andrews, Mr Thomas, jr    1st  39.00  NaN         0        0
9               Artagaveytia, Mr Ramon    1st  71.00  NaN         0        0

In [112]:
dataframe[dataframe.index != 0].head()

Name PClass    Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00     NaN   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92     NaN   
5                             Anderson, Mr Harry    1st  47.00     NaN   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1  
4         1        0  
5         1        0

## 3.12 Dropping Duplicate Rows

In [113]:
dataframe.drop_duplicates().head()

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00     NaN   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92     NaN   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [117]:
dataframe["Sex"].drop_duplicates()

0    female
2       NaN
Name: Sex, dtype: object

## 3.13 Grouping Rows by Values

In [123]:
dataframe.Sex.replace(np.nan, 'male', inplace=True)

In [124]:
dataframe.groupby('Sex').mean()

Age  Survived  SexCode
Sex                                 
female  29.396424  0.666667      1.0
male    31.014338  0.166863      0.0

In [126]:
dataframe.groupby('Survived')[['Name']].count()

Name
Survived      
0          863
1          450

In [127]:
# create date range
time_index = pd.date_range('06/06/2017', periods=100000, freq='30S')

In [128]:
# Create DataFrame
df = pd.DataFrame(index=time_index)

In [131]:
# Create column of random values
df['Sale_Amount'] = np.random.randint(1, 10, 100000)

In [132]:
df.head()

Sale_Amount
2017-06-06 00:00:00            1
2017-06-06 00:00:30            8
2017-06-06 00:01:00            9
2017-06-06 00:01:30            9
2017-06-06 00:02:00            9

In [133]:
# Group rows by week, calculate sum per week
df.resample("W").sum()

Sale_Amount
2017-06-11        85893
2017-06-18       101431
2017-06-25       100495
2017-07-02       100480
2017-07-09       100902
2017-07-16        10202

In [134]:
df.head(3)

Sale_Amount
2017-06-06 00:00:00            1
2017-06-06 00:00:30            8
2017-06-06 00:01:00            9

In [135]:
# Group by two weeks, calculate mean
df.resample('2W').mean()

Sale_Amount
2017-06-11     4.970660
2017-06-25     5.008085
2017-07-09     4.994593
2017-07-23     4.904808

In [136]:
# Group by month, counts rows
df.resample('M').count()

Sale_Amount
2017-06-30        72000
2017-07-31        28000

In [137]:
df.resample('M', label='left').count()

Sale_Amount
2017-05-31        72000
2017-06-30        28000

## 3.15 Looping Over a Column

In [138]:
for name in dataframe['Name'][:2]:
  print(name.upper())

ALLEN, MISS ELISABETH WALTON
ALLISON, MISS HELEN LORAINE


In [139]:
[name.upper() for name in dataframe['Name'][:2]]

['ALLEN, MISS ELISABETH WALTON', 'ALLISON, MISS HELEN LORAINE']

## 3.16 Applying a Function Over All Elements in a Column

In [140]:
def uppercase(x):
  return x.upper()

In [142]:
dataframe["Name"].apply(uppercase)[:5]

0                     ALLEN, MISS ELISABETH WALTON
1                      ALLISON, MISS HELEN LORAINE
2              ALLISON, MR HUDSON JOSHUA CREIGHTON
3    ALLISON, MRS HUDSON JC (BESSIE WALDO DANIELS)
4                    ALLISON, MASTER HUDSON TREVOR
Name: Name, dtype: object

## 2.17 Applying a Function to Groups

In [143]:
dataframe.groupby('Sex').apply(lambda x: x.count())

Name  PClass  Age  Sex  Survived  SexCode
Sex                                              
female   462     462  288  462       462      462
male     851     851  468  851       851      851

In [145]:
dataf = dataframe.copy()

In [146]:
dataf.head()

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [148]:
dataf[["PClass", 'Sex']] = dataf[["PClass", 'Sex']].astype('category')
dataf.dtypes

Name          object
PClass      category
Age          float64
Sex         category
Survived       int64
SexCode        int64
dtype: object

In [149]:
dataf[["PClass", 'Sex']] = dataf[["PClass", 'Sex']].apply(lambda x: x.values.codes)

In [151]:
dataf.head(10)

Name  PClass    Age  Sex  \
0                   Allen, Miss Elisabeth Walton       1  29.00    0   
1                    Allison, Miss Helen Loraine       1   2.00    0   
2            Allison, Mr Hudson Joshua Creighton       1  30.00    1   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)       1  25.00    0   
4                  Allison, Master Hudson Trevor       1   0.92    1   
5                             Anderson, Mr Harry       1  47.00    1   
6               Andrews, Miss Kornelia Theodosia       1  63.00    0   
7                         Andrews, Mr Thomas, jr       1  39.00    1   
8   Appleton, Mrs Edward Dale (Charlotte Lamson)       1  58.00    0   
9                         Artagaveytia, Mr Ramon       1  71.00    1   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0  
5         1        0  
6         1        1  
7         0        0  
8         1        1  
9         0        0

## 3.18 Concatenating DataFrames

In [153]:
# Create  DataFrame
data_a = {
    'id': ['1', '2', '3'],
    'first': ['Alex', 'Amy', 'Allen'],
    'last': ['Anderson', 'Ackerman', 'Ali']}

df_a = pd.DataFrame(data_a)

data_b = {
    'id': ['4', '5', '6'],
    'first': ['Billy', 'Brian', 'Bran'],
    'last': ['Bonder', 'Black', 'Balwner']}

df_b = pd.DataFrame(data_b)
df_b.head()

id  first     last
0  4  Billy   Bonder
1  5  Brian    Black
2  6   Bran  Balwner

In [157]:
pd.concat([df_a, df_b], axis=0)

id  first      last
0  1   Alex  Anderson
1  2    Amy  Ackerman
2  3  Allen       Ali
0  4  Billy    Bonder
1  5  Brian     Black
2  6   Bran   Balwner

In [158]:
row = pd.Series([10, 'Chris', 'Chillon'], index=['id', 'first', 'last'])

In [159]:
df_a.append(row, ignore_index=True)

id  first      last
0   1   Alex  Anderson
1   2    Amy  Ackerman
2   3  Allen       Ali
3  10  Chris   Chillon

In [161]:
pd.concat([df_a, df_b], ignore_index=True)

id  first      last
0  1   Alex  Anderson
1  2    Amy  Ackerman
2  3  Allen       Ali
3  4  Billy    Bonder
4  5  Brian     Black
5  6   Bran   Balwner

In [162]:
_.set_index('id')

first      last
id                 
1    Alex  Anderson
2     Amy  Ackerman
3   Allen       Ali
4   Billy    Bonder
5   Brian     Black
6    Bran   Balwner

## 3.19 Merging DataFrames

In [163]:
employee_data = {
    "employee_id":['1', '2', '3', '4'],
    'name':['Amy Jones', 'Allen Keys', 'Alice Bees', 'Tim Horton']
}
df_employees = pd.DataFrame(employee_data, columns=['employee_id', 'name'])

In [164]:
sales_data = {
    'employee_id':['3', '4', '5', '6'],
    'total_sales':[23456, 2512, 23445, 1455]
}
df_sales = pd.DataFrame(sales_data, columns=['employee_id', 'total_sales'])

In [165]:
df_sales.head()

employee_id  total_sales
0           3        23456
1           4         2512
2           5        23445
3           6         1455

In [167]:
pd.merge(df_employees, df_sales, on='employee_id')

employee_id        name  total_sales
0           3  Alice Bees        23456
1           4  Tim Horton         2512

In [169]:
pd.merge(df_employees, df_sales, on='employee_id', how='outer')

employee_id        name  total_sales
0           1   Amy Jones          NaN
1           2  Allen Keys          NaN
2           3  Alice Bees      23456.0
3           4  Tim Horton       2512.0
4           5         NaN      23445.0
5           6         NaN       1455.0

In [170]:
pd.merge(df_employees, df_sales, on='employee_id', how='left')

employee_id        name  total_sales
0           1   Amy Jones          NaN
1           2  Allen Keys          NaN
2           3  Alice Bees      23456.0
3           4  Tim Horton       2512.0

In [171]:
pd.merge(df_employees, df_sales, on='employee_id', how='right')

employee_id        name  total_sales
0           3  Alice Bees        23456
1           4  Tim Horton         2512
2           5         NaN        23445
3           6         NaN         1455

In [172]:
pd.merge(
    df_employees,
    df_sales,
    left_on='employee_id',
    right_on='employee_id')

employee_id        name  total_sales
0           3  Alice Bees        23456
1           4  Tim Horton         2512

# 4. Handling Numerical Data

## 4.1 Rescaling a Feature

You need to rescale the values of a numerical feature to be between two values.

In [174]:
from sklearn import preprocessing

In [175]:
# Create feature
feature = np.array([
                    [-500.5],
                    [-100.1],
                    [0],
                    [100.1],
                    [900.9]])

In [179]:
# Create scaler
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))

In [180]:
# Scale feature
scaled_feature = minmax_scale.fit_transform(feature)

In [181]:
# Show feature
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

**Formule**

x  = x − min(x)  / max(x) − min(x)