# Numpy

Nous allons voir les notions avancées de numpy et les différentes manipulations avec 

### Importation

In [1]:
import numpy as np

### Création de tableaux

Un tableau numpy ne contient que les élèments d'un même type

**1. Depuis une liste**

In [2]:
array = np.array([1, 4, 2, 5, 3])

In [3]:
array

array([1, 4, 2, 5, 3])

In [4]:
# Avec le type float
arr = np.array([3.14, 8, 2.4, 5])
arr

array([3.14, 8.  , 2.4 , 5.  ])

*Spécifier le type de données*

In [5]:
arr = np.array([1, 2, 3, 4], dtype='float16')

In [6]:
arr

array([1., 2., 3., 4.], dtype=float16)

In [7]:
arr.astype('int32')

array([1, 2, 3, 4], dtype=int32)

In [8]:
arr

array([1., 2., 3., 4.], dtype=float16)

In [9]:
arr = np.arange(10)

In [10]:
arr.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

*Multiple dimension*

In [12]:
arr = np.array([range(i, i + 3) for i in [2, 4, 6]])
arr

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [13]:
np.arange(2, 9)

array([2, 3, 4, 5, 6, 7, 8])

**2. Créer directement avec Numpy**

*Tableau constitué des entiers qui valent tous zéro*

In [14]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

*Tableau des entiers qui valent tous 1*

In [15]:
ones = np.ones((3, 5))

In [16]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
ones = np.ones((3, 5), dtype='float32')
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

*Tableau rempli d'une valeur spécifique*

In [18]:
full = np.full((3, 5), 3.14)
full

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [19]:
np.full((3, 5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.full((2, 4), 5, dtype=float)

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

*Tableau selon une plage donné des valeurs*

In [21]:
arr = np.arange(0, 20, 2)

In [22]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

*Tableau des valeurs uniformément séparées*

In [23]:
# Créer un tableau de 5 valeurs compris entre '0' et '1'
arr = np.linspace(0, 1, 5)

In [24]:
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

*Nombre Aléatoire*

In [25]:
np.random.random((3, 3))

array([[0.60880396, 0.18459543, 0.91440332],
       [0.43579281, 0.7990774 , 0.30762436],
       [0.39718657, 0.97205161, 0.68550979]])

*Une matrice identité*

In [26]:
# dimension 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Autres tests**

In [27]:
np.random.normal((5), size=10)

array([3.66108532, 5.30850394, 4.88678811, 5.34382446, 5.9964655 ,
       4.56755123, 4.70892171, 4.94512763, 4.36446327, 3.95184514])

#### Propriété de Matrice

**Dimension du tableau**

In [28]:
arr = np.random.randint(10, size=6)

In [29]:
print("dimension de la matrice {}".format(arr.ndim))

dimension de la matrice 1


**Forme de la matrice**

In [30]:
print("Forme de la matrice {}".format(arr.shape))

Forme de la matrice (6,)


**Taille de la matrice**

In [31]:
# Nombre d'élèments que contient la matrice
print("Taille de la matrice {}".format(arr.size))

Taille de la matrice 6


**Type de données de la matrice**

In [32]:
print("Type de données de la matrice '{}'".format(arr.dtype))

Type de données de la matrice 'int64'


## Indexing et Slicing

### Accèder à un seul élèment

In [33]:
arr = np.arange(0, 11,)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[0]

0

**Tableau à plusieurs dimensions**

In [36]:
arr2 = np.random.randint(10, size=(3, 4))
arr2

array([[2, 7, 2, 8],
       [6, 5, 0, 5],
       [8, 5, 1, 8]])

In [37]:
arr2[0, 1]

7

In [38]:
arr[1] = '100'
arr

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [39]:
arr.dtype

dtype('int64')

In [40]:
arr[2] = 3.14
arr

array([  0, 100,   3,   3,   4,   5,   6,   7,   8,   9,  10])

### Accèder à plusieurs élèments

**synthaxe:**

array[debut:fin:pas]

In [41]:
# De zéro à 10 avec un pas de 2
arr[0:10:2]

array([0, 3, 4, 6, 8])

In [42]:
# Cinq premiers élèments
arr[:5]

array([  0, 100,   3,   3,   4])

In [43]:
# Les élèements à partir du cinquième
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
# Inverser le tableau
arr[::-1]

array([ 10,   9,   8,   7,   6,   5,   4,   3,   3, 100,   0])

In [45]:
arr2

array([[2, 7, 2, 8],
       [6, 5, 0, 5],
       [8, 5, 1, 8]])

In [46]:
# Accèder à la premier ligne
arr2[0, :]

array([2, 7, 2, 8])

In [47]:
# Accèder à tous les élèments de la prémière colonne
arr2[:, 0]

array([2, 6, 8])

In [48]:
# Accèder aux deux premier élèments de lignes 1 et 2
arr2[:2, :2]

array([[2, 7],
       [6, 5]])

In [49]:
arr2[0:2]

array([[2, 7, 2, 8],
       [6, 5, 0, 5]])

### Concatenation

In [50]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [51]:
# Appliquer la concatenation
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [52]:
np.vstack([x, y])

array([[1, 2, 3],
       [3, 2, 1]])

In [53]:
np.hstack([x, y])

array([1, 2, 3, 3, 2, 1])

In [54]:
arr2

array([[2, 7, 2, 8],
       [6, 5, 0, 5],
       [8, 5, 1, 8]])

In [55]:
x

array([1, 2, 3])

In [56]:
arr3 = np.array([
    [9, 8, 7],
    [6, 5, 4]
])

In [57]:
arr3

array([[9, 8, 7],
       [6, 5, 4]])

In [58]:
# Concatenation horizontale
np.vstack([x, arr3])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

### Opérations sur le tableau

In [59]:
tableau = np.random.randint(1, 100, size=100000)
tableau

array([45, 47, 37, ...,  3, 87, 34])

In [60]:
# Le temps d'éxécution pour faire l'opération inverse
%timeit (1.0 / tableau)

220 µs ± 7.99 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### Fonctions usuelles

In [61]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [62]:
print("Opérations basiques et usuelles")
print("x = ", x)
print("x + 5 = ", x + 5)
print("x - 5 = ", x - 5)
print("x * 2 = ", x * 2)
print("x / 2 = ", x / 5)
print("x // 2 = ", x // 5)

Opérations basiques et usuelles
x =  [0 1 2 3]
x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 2 =  [0 2 4 6]
x / 2 =  [0.  0.2 0.4 0.6]
x // 2 =  [0 0 0 0]


**Fonction internes à Numpy**

In [63]:
x = [-2, -1, 2, 1]
x

[-2, -1, 2, 1]

In [64]:
print("Valeur absolue de x: ", np.abs(x))
print("Exponentielle x ", np.exp(x))
print("Logarithme de x ", np.log(np.abs(x)))

Valeur absolue de x:  [2 1 2 1]
Exponentielle x  [0.13533528 0.36787944 7.3890561  2.71828183]
Logarithme de x  [0.69314718 0.         0.69314718 0.        ]


#### Opérations Booléennes

In [65]:
arr = np.random.rand(3, 3)

In [66]:
arr

array([[0.24400201, 0.12732393, 0.49771157],
       [0.74632435, 0.71289328, 0.09783513],
       [0.85054003, 0.49221145, 0.53535118]])

In [67]:
arr >  0.5

array([[False, False, False],
       [ True,  True, False],
       [ True, False,  True]])

In [68]:
arr[arr > 0.5]

array([0.74632435, 0.71289328, 0.85054003, 0.53535118])

In [69]:
np.where(arr > 0.5)

(array([1, 1, 2, 2]), array([0, 1, 0, 2]))

In [70]:
result = np.where(arr > 0.5, 10, 20)
result

array([[20, 20, 20],
       [10, 10, 20],
       [10, 20, 10]])

#### Aggrégation

In [71]:
tab = np.random.random(100)
tab

array([0.00190927, 0.58587203, 0.44820741, 0.02650844, 0.48426388,
       0.90516818, 0.52938778, 0.56596033, 0.86503003, 0.93574994,
       0.67968994, 0.29816812, 0.68835004, 0.11086572, 0.87763378,
       0.39325317, 0.51679082, 0.87730775, 0.8486079 , 0.43001858,
       0.72193447, 0.70148511, 0.86518464, 0.12527428, 0.62524452,
       0.9280415 , 0.01999154, 0.51616767, 0.45202361, 0.02315584,
       0.77063551, 0.62106339, 0.38027911, 0.13434473, 0.58578021,
       0.16579027, 0.41522721, 0.68036883, 0.03229522, 0.28890933,
       0.46187155, 0.74110623, 0.39762596, 0.38709665, 0.52212383,
       0.28668255, 0.00112905, 0.92125883, 0.36388795, 0.2246658 ,
       0.34022458, 0.70482763, 0.34895398, 0.77083413, 0.28662548,
       0.34027488, 0.82752447, 0.05879353, 0.53915047, 0.68080617,
       0.43657871, 0.67561769, 0.67068896, 0.49231869, 0.44851149,
       0.14362003, 0.69798907, 0.786412  , 0.48252042, 0.56338176,
       0.6819232 , 0.04119994, 0.90063216, 0.89163461, 0.63725

In [72]:
# Somme des valeurs
np.sum(tab)

50.38148333288531

In [73]:
arr3

array([[9, 8, 7],
       [6, 5, 4]])

In [74]:
# L'index de la valeur minimale
np.argmin(arr3)

5

In [75]:
# Index de la valeur maximale
np.argmax(arr3)

0

In [76]:
# Valeur minimale
arr3.min()

4

In [77]:
# Valeur maximale
arr3.max()

9

In [78]:
# Ecart-type de valeurs
arr3.std()

1.707825127659933

In [79]:
# Moyenne de valeurs
arr3.mean()

6.5

In [80]:
# Percentile de valeurs
np.percentile(arr3, 1)

4.05

**Inverser l'ordre de la matrice**

In [81]:
x = np.arange(3)
x

array([0, 1, 2])

In [82]:
x[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [83]:
_[np.newaxis, :]

array([[[0],
        [1],
        [2]]])

In [85]:
a = np.arange(3)
a

array([0, 1, 2])

In [86]:
b = a[:, np.newaxis]

In [87]:
b

array([[0],
       [1],
       [2]])

In [88]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])